
type = "service_account"
project_id = "crew-manager-464618"
private_key_id = "2f5f0d693572e5a2d5661abc1a34ff84d50c0d61"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCyK4r93+kU54WH
385lxK8SZXR2OvQOjqz5YK64PZkpxeVtq6k7cP7Zjw1IpLwakH2kzyXvfdu9BS0d
8hIr40qN4Nvr9xzvS5rbjRoEliFhJXcXoCYPU+gSHaCVEYyQ5jVsphWYQXCXWVAe
lJclm7thKEzHQH7+hAiV6fjYcUCfqf1rAjus88oObAMtj6eOVIop5xFZPZ5FtvuZ
S0RkJHUNz+9qBmhwdYalpyjXwOjPC5itvughW/XvRre7buqnpaUXisrFwszLHSla
+h8eEfJo0ZHI/NkZUhzbSyHTCJOp914Bt3r/n4jxls3juZOkYECO22exDZklyZzI
jitbTg9JAgMBAAECgf8+H48UDqMwlH1J9WP783nzMy/oaxOVhe0HBuXk6g9fGb/3
wHtsLCSwPR6PSAXUkrGFpy6xfXPp9GQWEwJnlEB84oLYUA5rSSg1uq4IfaXEWC1l
FZCRQYW714BdPNODUPJP0WhtCaEyYXHdaJCIDHWk0m6FO9lVCczoYFD8fGhC4Ytw
lm5LyJLKltJJ3kQAWUEKsPo2/y4p30PdYd2HagRzn2ejE6luWD70tr42zIC5DXpc
9SYBN6ghzpoVrvdJjEZzfQVH6XmObPgDHfGtUvaMGA/KAJ9o7162MUlmTCmFxUbC
1ohIk6OiwPbqdLTdz5A3fwXYBfaqoGVzvVmYXkECgYEA7Y/6LnXXQNEg3WgnOPr/
jeMgpOEPfYaGYuMuTAKCOOYHBKaghp0DoSvBQQS1CZAyTMQgAmQI/WS9jZlsJqIb
5i9KpOWavluQRsvvvB3F9bKmqZ1c5uvFvsz3PBDj+8ebDiL/TptniR4YdjSuIOpl
8zrQBFb8+bXZtVsycrN3w5kCgYEAv/+GnPJ8Kv8ZC1quVjr8Kld056bBlR9SMUNh
sAyRk715KYX+h4fnLigj0NB30q/n8rNzXeRtI4Osr0Hmn6QxNLOHp6n+sYXBUu3Y
3oEzaZXXfenAOYOO6SQi358k9lw8qHssX0Gx+RI2fg0qKresuhhlyv0zqLnWDHwy
KDqR9zECgYEAvfqX/jOq8mDLwYQbacwANr3eSzzYoG/GZKp9Sbfv4ATEtAl08nH6
hxdwsshK5tzz/MQTPRY2wj2gAO8iuDqHySskrH4ZpAWheZx5mZzNxNEbyyTXOKxw
NUfAp75yM9XKwCFovro0sEjrEwzJ+/S3ly3/UJkoMaIl+ox16ZhwPHECgYAgPwtd
ysAd/JA5Pvau1uNJPT0ONwymPgdw7K84gTPmC1mRJscT/jhOoUE6rfih8xdSxN7o
cxf9cf0Lxla0k0AMaOasuzlimWNZyUa2QB7haeAybpLxVe4nrAELa9AqbF1nsqBG
M2NvwKZUT2O4nvasnrJiAFqvyN5xZF6MMSIY0QKBgG90KO4SuYd81m6IXwzL6Ouw
Z7uDTU9EjyENy1joELYhAO8VDIMgJoGn1ZQhCkmu/7Bysr6VknxqZxtOZelFfktJ
ZXlXhdZL6RFDudGUptiYpXK9EwGuO57b2RTMRqScOUMHZ0QpNlleWnO2GhaoU3H0
J28/vz72tCEt9BAxx4HZ
-----END PRIVATE KEY-----
"""
client_email = "streamlit-access@crew-manager-464618.iam.gserviceaccount.com"
client_id = "111088891421942452997"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access@crew-manager-464618.iam.gserviceaccount.com"
